.TH "yajl_gen_config" 3 "18 Dec 2009" "Version 1.0.8" "YAJL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
yajl_gen_config \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <yajl_gen.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBbeautify\fP"
.br
.ti -1c
.RI "const char * \fBindentString\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
configuration structure for the generator 
.SH "Field Documentation"
.PP 
.SS "unsigned int \fByajl_gen_config::beautify\fP"generate indented (beautiful) output 
.SS "const char* \fByajl_gen_config::indentString\fP"an opportunity to define an indent string. such as \\t or some number of spaces. default is four spaces ' '. This member is only relevant when beautify is true 

.SH "Author"
.PP 
Generated automatically by Doxygen for YAJL from the source code.
