.TH "yajl_common.h" 3 "18 Dec 2009" "Version 1.0.8" "YAJL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
yajl_common.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fByajl_alloc_funcs\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBYAJL_MAX_DEPTH\fP   128"
.br
.ti -1c
.RI "#define \fBYAJL_API\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void *(* \fByajl_malloc_func\fP )(void *ctx, unsigned int sz)"
.br
.ti -1c
.RI "typedef void(* \fByajl_free_func\fP )(void *ctx, void *ptr)"
.br
.ti -1c
.RI "typedef void *(* \fByajl_realloc_func\fP )(void *ctx, void *ptr, unsigned int sz)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define YAJL_API"
.SS "#define YAJL_MAX_DEPTH   128"
.SH "Typedef Documentation"
.PP 
.SS "typedef void(* \fByajl_free_func\fP)(void *ctx, void *ptr)"pointer to a free function, supporting client overriding memory allocation routines 
.SS "typedef void*(* \fByajl_malloc_func\fP)(void *ctx, unsigned int sz)"pointer to a malloc function, supporting client overriding memory allocation routines 
.SS "typedef void*(* \fByajl_realloc_func\fP)(void *ctx, void *ptr, unsigned int sz)"pointer to a realloc function which can resize an allocation. 
.SH "Author"
.PP 
Generated automatically by Doxygen for YAJL from the source code.
